{% set name = "ansible" %}
{% set version = "2.5.0" %}
{% set sha256 = "714ede4b0f5455eb2dd2536d8cabb42ab439f52b5ac902308ad027b46f68e6dc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [py3k]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - paramiko
    - jinja2
    - pyyaml
    - httplib2
    - pycrypto
    - six
    - shade
    - boto

test:
  imports:
    - ansible
    - ansible.constants
    - ansible.errors
    - ansible.utils
    
about:
  home: http://github.com/ansible/ansible
  license: GPL-3.0
  license_file: COPYING
  summary: 'Ansible is a radically simple IT automation platform'

  description: |
    Ansible is a radically simple IT automation platform 
    that makes your applications and systems easier to deploy.
    Includes support for OpenStack (shade) and EC2 (AWS), extra
    batteries included.
  doc_url: https://www.ansible.com/
  dev_url: https://github.com/ansible/ansible

extra:
  recipe-maintainers:
    - souravsingh
    - brainstorm
