{% set name = "ansible" %}
{% set version = "2.10.3" %}
{% set sha256 = "eb1d08b9b98a60e90e7123a12f40770780f29f9d73168da55d449106a9f4d348" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - setuptools
    - paramiko
    - jinja2
    - pyyaml
    - httplib2
    - cryptography
    - six
    - openstacksdk
    - boto

test:
  imports:
    - ansible
    - ansible.constants
    - ansible.errors
    - ansible.utils

about:
  home: http://github.com/ansible/ansible
  license: GPL-3.0-only
  license_file: COPYING
  summary: Ansible is a radically simple IT automation platform

  description: |
    Ansible is a radically simple IT automation platform
    that makes your applications and systems easier to deploy.
    Includes support for OpenStack (shade) and EC2 (AWS), extra
    batteries included.
  doc_url: https://www.ansible.com/
  dev_url: https://github.com/ansible/ansible

extra:
  recipe-maintainers:
    - brainstorm
