{% set name = "ansible" %}
{% set version = "8.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 935a6921ffb034aa18e6507b49e401676cd15243d6faa5e05e221008bf725c97

build:
  number: 0
  # ansible-core has importlib_resources >=5.0 <5.1 as requirements, this is not solvable in conda-forge
  # https://github.com/ansible/ansible/blob/0982d5fa98e64d241249cfd6dd024e70ae20d0c3/requirements.txt#L10-L12
  skip: true  # [win or py<310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - setuptools
    - ansible-core >=2.15.1,<2.16
    - paramiko
    - jinja2
    - pyyaml
    - httplib2
    - cryptography
    - six
    - openstacksdk
    - boto

test:
  requires:
    - pip
  commands:
    - ansible --version
    - pip check
  imports:
    - ansible
    - ansible.constants
    - ansible.errors
    - ansible.utils

about:
  home: http://github.com/ansible/ansible
  license: GPL-3.0-only
  license_file: COPYING
  summary: Ansible is a radically simple IT automation platform

  description: |
    Ansible is a radically simple IT automation platform
    that makes your applications and systems easier to deploy.
    Includes support for OpenStack (shade) and EC2 (AWS), extra
    batteries included.
  doc_url: https://www.ansible.com/
  dev_url: https://github.com/ansible/ansible

extra:
  recipe-maintainers:
    - brainstorm
    - tschoonj
    - pavelzw
