{% set python_min = "3.11" %}
{% set name = "ansible" %}
{% set version = "11.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d25a7f26bf5821f8043bc806019822fd2810bd65e6b6bafb698bbeedadba72bf

build:
  entry_points:
    - ansible-community=ansible_collections.ansible_community:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - ansible-core >=2.18.4,<2.19.dev0
    # https://docs.ansible.com/ansible/latest/user_guide/windows_faq.html#can-ansible-run-on-windows
    - __unix

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - ansible --version
    - pip check
    - ansible-community --help
  imports:
    - ansible_collections

about:
  home: http://github.com/ansible/ansible
  license: GPL-3.0-only
  license_file: COPYING
  summary: Ansible is a radically simple IT automation platform

  description: |
    Ansible is a radically simple IT automation platform
    that makes your applications and systems easier to deploy.
    Includes support for OpenStack (shade) and EC2 (AWS), extra
    batteries included.
  doc_url: https://www.ansible.com/
  dev_url: https://github.com/ansible/ansible

extra:
  recipe-maintainers:
    - brainstorm
    - tschoonj
    - pavelzw
